const express = require("express");
const UserRouter = require("./router/User");
const TaskRouter = require("./router/Tasks");
const app = express();
const jwt = require("jsonwebtoken");
const port = process.env.PORT || 3000;
app.use(express.json());
app.use(UserRouter);
app.use(TaskRouter);
app.listen(port, () => console.log(`running at ${port}`));
